### ISSUE TITLE
Refactor for JOSE Split

### ISSUE THREAD

**Issue by EternalDeiwos** [anvilresearch/jwt#6]
JWT/JWD to use [_@trust/jwk_](https://github.com/anvilresearch/jwk) for signing/encryption/decryption operations and [_@trust/keycache_](https://github.com/anvilresearch/keycache) for signature verification.

**Comment by EternalDeiwos** [comment]
It should be noted that JWT method signatures and usage should remain the same; only the underlying functionality would be changing.

**Comment by christiansmith** [comment]
I'm leaning towards having JWT verification work in the way we've discussed for keycache, but possibly using JWA directly in cases where the JWK is passed as an argument. It's the responsibility of the JWT.verify method to ensure signatures are properly verified, and that means it should control the cryptographic operation, not delegate to some injected object method.

That said, there's no reason we shouldn't take advantage of sign/verify methods directly on JWK in cases where that makes sense, such as when the keys are resolved and imported _within_ the JWT/JWD/JW* verify method.

Apologies if these thoughts are inconsistent, self-contradictory, etc. Been a looooong day, but I wanted to capture this for further discussion. Recommend that we continue to reserve judgment while exploring these options to their logical extremes.

**Comment by EternalDeiwos** [comment]
Based on what we discussed at the crypto hangout (24/08/17), I have updated my [gist](https://gist.github.com/EternalDeiwos/b838a35fa23909074c5195801cad422a#verification-and-deserialization) with a proposal for the API/inner workings of JWT; specifically, with my understanding of the discussion around how `JWT.verify` should work.

Also please tell me what you think of the Key management section of the gist linked above w.r.t. only using JWKs that are resolved/imported within the `JWT.verify` method.

**Comment by EternalDeiwos** [comment]
#10 Merged. Closing this issue.
